### ISSUE TITLE
utf8_encode is deprecated

### ISSUE THREAD

**Issue by mathchat900** [Hebbinkpro/PocketMap#23] opened 2023-12-28 12:48 UTC
Hi, I had a crash with your plugin with your version 0.5.0 of pocketmap here is the crash:

[12:34:28.508] [Server thread/INFO]: Activation de PocketMap v0.5.0
[12:34:28.523] [Server thread/CRITICAL]: ErrorException: "Function utf8_encode() is deprecated" (EXCEPTION) in "plugins/PocketMap-main/src/Hebbinkpro/PocketMap/textures/TerrainTextures" at line 146
--- Stack trace ---
  #0 plugins/PocketMap-main/src/Hebbinkpro/PocketMap/textures/TerrainTextures(146): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 8192, string[36] Function utf8_encode() is deprecated, string[119] C:\Users\Matheo\Desktop\ServeurPM5 - Copie\plugins\PocketMap-main\src\Hebbinkpro, int 146)
  #1 plugins/PocketMap-main/src/Hebbinkpro/PocketMap/textures/TerrainTextures(63): Hebbinkpro\PocketMap\textures\TerrainTextures->getAllResourcePacks(object pocketmine\resourcepacks\ResourcePackManager#44664, null)
  #2 plugins/PocketMap-main/src/Hebbinkpro/PocketMap/PocketMap(307): Hebbinkpro\PocketMap\textures\TerrainTextures::generate(object Hebbinkpro\PocketMap\PocketMap#180256, string[80] C:/Users/Matheo/Desktop/ServeurPM5 - Copie/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\textures\TerrainTexturesOptions#45121)
  #3 plugins/PocketMap-main/src/Hebbinkpro/PocketMap/PocketMap(165): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()

**Comment by Hebbinkpro** [comment] 2023-12-28 13:07
Hi, thanks for reporting the issue.
This is caused by the new PHP 8.2 binaries, I will fix it asap.

**Comment by Hebbinkpro** [comment] 2023-12-29 11:11
Fixed in v0.5.1

**Closed as completed by Hebbinkpro** 2023-12-29 11:11 UTC

**Comment by mathchat900** [comment] 2023-12-30 00:43
ok thanks
